/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_Manager;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sheharyar saeed 190880 
 * BSSE B - 4
 */
public class AddBranch extends javax.swing.JFrame {
    Bank bank;
    Branch branch;
    /**
     * Creates new form NewJFrame
     */
     AddBranch() {
        initComponents();
    }
     AddBranch(Bank bnk) {
        initComponents();
        bank = bnk;
        branchesdisplay.setText(bank.displayBranch());
        tfbranchcode.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        tfbranchcode = new javax.swing.JTextField();
        tfbranchcity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        branchesdisplay = new javax.swing.JTextArea();
        tfzoneheadoffice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addcustomerbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        addCustomerMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(33, 33, 33));

        savebutton.setBackground(new java.awt.Color(87, 82, 62));
        savebutton.setText("Save");
        savebutton.setPreferredSize(new java.awt.Dimension(100, 30));
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        tfbranchcode.setBackground(new java.awt.Color(242, 190, 36));
        tfbranchcode.setForeground(new java.awt.Color(87, 82, 62));

        tfbranchcity.setBackground(new java.awt.Color(242, 190, 36));
        tfbranchcity.setForeground(new java.awt.Color(87, 82, 62));

        jLabel1.setForeground(new java.awt.Color(87, 82, 62));
        jLabel1.setText("Branch Code");

        jLabel2.setForeground(new java.awt.Color(87, 82, 62));
        jLabel2.setText("Branch City");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 82, 62));
        jLabel3.setText("Add New Branch");

        branchesdisplay.setBackground(new java.awt.Color(242, 190, 36));
        branchesdisplay.setColumns(20);
        branchesdisplay.setForeground(new java.awt.Color(87, 82, 62));
        branchesdisplay.setRows(5);
        branchesdisplay.setText("Display Branches :");
        jScrollPane2.setViewportView(branchesdisplay);

        tfzoneheadoffice.setBackground(new java.awt.Color(242, 190, 36));
        tfzoneheadoffice.setForeground(new java.awt.Color(87, 82, 62));

        jLabel4.setForeground(new java.awt.Color(87, 82, 62));
        jLabel4.setText("Zone Head Office Code");

        addcustomerbutton.setBackground(new java.awt.Color(87, 82, 62));
        addcustomerbutton.setText("Add Customer");
        addcustomerbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        addcustomerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomerbuttonActionPerformed(evt);
            }
        });

        jMenuBar1.setForeground(new java.awt.Color(87, 82, 62));

        JMenu1.setText("File");

        addCustomerMI.setText("Add Customer");
        addCustomerMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMIActionPerformed(evt);
            }
        });
        JMenu1.add(addCustomerMI);

        jMenuBar1.add(JMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfzoneheadoffice, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfbranchcity, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addcustomerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfbranchcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfzoneheadoffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcustomerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        String code = tfbranchcode.getText();
        if(bank.getBranch(code)==null){
            String city = tfbranchcity.getText();
            String ZHO = tfzoneheadoffice.getText();
        
            branch = new Branch(code,city,ZHO);
            bank.addBranch(branch);
            
            if(bank.getBranch(ZHO)!=null){
                branchesdisplay.setText(bank.displayBranch());
            }
            else{
                bank.removeBranch(code);
                showMessageDialog(null, "Zone Head Office Didn't Found!", "ERROR", ERROR_MESSAGE);
            }
            //bank.setbranchZHO(code,ZHO);
        }
        else{
            showMessageDialog(null, "Branch Already Exist!", "ERROR", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_savebuttonActionPerformed

    private void addCustomerMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMIActionPerformed
        // TODO add your handling code here:
        AddCustomerFrame jFrame = new AddCustomerFrame(bank,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_addCustomerMIActionPerformed

    private void addcustomerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomerbuttonActionPerformed
        // TODO add your handling code here:
        AddCustomerFrame jFrame = new AddCustomerFrame(bank,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_addcustomerbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBranch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddBranch().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JMenuItem addCustomerMI;
    private javax.swing.JButton addcustomerbutton;
    private javax.swing.JTextArea branchesdisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField tfbranchcity;
    private javax.swing.JTextField tfbranchcode;
    private javax.swing.JTextField tfzoneheadoffice;
    // End of variables declaration//GEN-END:variables
}
