package Bank_Manager;

import java.text.DateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sheharyar saeed 190880 
 * BSSE B - 4
 */
public class AddCurrentAccountFrame extends javax.swing.JFrame {
    Bank bank;
    Customer customer;
    Branch branch;
    /**
     * Creates new form AddAccountFrame
     */
     AddCurrentAccountFrame() {
        initComponents();
    }
     AddCurrentAccountFrame(Bank bnk) {
        initComponents();
        bank = bnk;
    }
     AddCurrentAccountFrame(Bank bnk,Customer cust, Branch brnch) {
        initComponents();
        bank = bnk;
        customer = cust;
        tfcustomerid.setText(customer.Cust_ID);
        branch = brnch;
        tfbranchcode.setText(branch.Branch_Code);
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        tfDoO.setText(dateFormat.format(date));
        tfaccountno.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfaccountbalance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDoO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfinterestrate = new javax.swing.JTextField();
        addaccountbutton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfbranchcode = new javax.swing.JTextField();
        tfaccountno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfcustomerid = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfaccountbalance.setBackground(new java.awt.Color(242, 190, 36));
        tfaccountbalance.setForeground(new java.awt.Color(87, 82, 62));

        jLabel5.setForeground(new java.awt.Color(87, 82, 62));
        jLabel5.setText("Branch Code");

        tfDoO.setBackground(new java.awt.Color(242, 190, 36));
        tfDoO.setForeground(new java.awt.Color(87, 82, 62));

        jLabel9.setForeground(new java.awt.Color(87, 82, 62));
        jLabel9.setText("Interest Rate (%)");

        jLabel10.setForeground(new java.awt.Color(87, 82, 62));
        jLabel10.setText("Date of Opening");

        tfinterestrate.setBackground(new java.awt.Color(242, 190, 36));
        tfinterestrate.setForeground(new java.awt.Color(87, 82, 62));

        addaccountbutton1.setBackground(new java.awt.Color(87, 82, 62));
        addaccountbutton1.setText("ADD");
        addaccountbutton1.setPreferredSize(new java.awt.Dimension(100, 30));
        addaccountbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccountbutton1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(87, 82, 62));
        jLabel6.setText("Account No");

        jLabel7.setForeground(new java.awt.Color(87, 82, 62));
        jLabel7.setText("Balance");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(87, 82, 62));
        jLabel8.setText("Add New Current Account");

        tfbranchcode.setBackground(new java.awt.Color(242, 190, 36));
        tfbranchcode.setForeground(new java.awt.Color(87, 82, 62));

        tfaccountno.setBackground(new java.awt.Color(242, 190, 36));
        tfaccountno.setForeground(new java.awt.Color(87, 82, 62));

        jLabel11.setForeground(new java.awt.Color(87, 82, 62));
        jLabel11.setText("Customer ID");

        tfcustomerid.setBackground(new java.awt.Color(242, 190, 36));
        tfcustomerid.setForeground(new java.awt.Color(87, 82, 62));

        jMenuBar1.setForeground(new java.awt.Color(87, 82, 62));

        JMenu1.setText("File");
        jMenuBar1.add(JMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(addaccountbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfinterestrate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfDoO, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfaccountno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfaccountbalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfaccountno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfinterestrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfDoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(addaccountbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addaccountbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccountbutton1ActionPerformed
        // TODO add your handling code here:
        String code = tfbranchcode.getText();
        if(bank.getBranch(code)!=null){
            String customerid = tfcustomerid.getText();
            if(bank.getBranch(code).getCustomer(customerid)!=null){
                String accno = tfaccountno.getText();
                if(!accno.isEmpty() && bank.getBranch(code).getAccount(accno)==null && bank.getBranch(code).getCustomer(customerid).getCA()!=null){
                    
                    double balance = Double.parseDouble(tfaccountbalance.getText());
                    double intrate = Double.parseDouble(tfinterestrate.getText());
                    String doo = tfDoO.getText();

                    branch = bank.getBranch(code);

                    Current_Account currentaccount = new Current_Account();
                    currentaccount.addCustomer(accno, balance, intrate, doo, branch, customer);
                    
                    bank.getBranch(code).getCustomer(customerid).setCA(currentaccount);
                    
                    branch.addAccount(currentaccount);

                    showMessageDialog(null, "Current Account is Added");
                    this.dispose();
                    
                }
                else{
                    showMessageDialog(null, "Incorrect ID or Account already Exist!", "ERROR", ERROR_MESSAGE);
                }
            }
            else{
                showMessageDialog(null, "Customer Didn't Found!", "ERROR", ERROR_MESSAGE);
            }
        }
        else{
            showMessageDialog(null, "Branch Didn't Found!", "ERROR", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addaccountbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCurrentAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCurrentAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCurrentAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCurrentAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddCurrentAccountFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JButton addaccountbutton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tfDoO;
    private javax.swing.JTextField tfaccountbalance;
    private javax.swing.JTextField tfaccountno;
    private javax.swing.JTextField tfbranchcode;
    private javax.swing.JTextField tfcustomerid;
    private javax.swing.JTextField tfinterestrate;
    // End of variables declaration//GEN-END:variables
}
