/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_Manager;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sheharyar saeed 190880 
 * BSSE B - 4
 */
public class AddCustomerFrame extends javax.swing.JFrame {
    Bank bank;
    Customer customer;
    Branch branch;
    /**
     * Creates new form AddAccountFrame
     */
     AddCustomerFrame() {
        initComponents();
    }
    AddCustomerFrame(Bank bnk) {
        initComponents();
        bank = bnk;
    }
     AddCustomerFrame(Bank bnk, Branch brnch) {
        initComponents();
        bank = bnk;
        branch = brnch;
        tfbranchcode.setText(branch.Branch_Code);
        tfcustomerid.requestFocus();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        tfbranchcode = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        tfcustomerid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfphoneno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfaddress = new javax.swing.JTextField();
        addcustomerbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        getloanbutton = new javax.swing.JButton();
        opencurrentaccountbutton = new javax.swing.JButton();
        opensavingaccountbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        addCurrentAccountMI = new javax.swing.JMenuItem();
        addSavingAccountMI = new javax.swing.JMenuItem();
        addLoanMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(87, 82, 62));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add New Customer");

        tfbranchcode.setBackground(new java.awt.Color(242, 190, 36));
        tfbranchcode.setForeground(new java.awt.Color(87, 82, 62));

        tfname.setBackground(new java.awt.Color(242, 190, 36));
        tfname.setForeground(new java.awt.Color(87, 82, 62));

        tfcustomerid.setBackground(new java.awt.Color(242, 190, 36));
        tfcustomerid.setForeground(new java.awt.Color(87, 82, 62));

        jLabel5.setForeground(new java.awt.Color(87, 82, 62));
        jLabel5.setText("Branch Code");

        tfphoneno.setBackground(new java.awt.Color(242, 190, 36));
        tfphoneno.setForeground(new java.awt.Color(87, 82, 62));

        jLabel9.setForeground(new java.awt.Color(87, 82, 62));
        jLabel9.setText("Address");

        jLabel10.setForeground(new java.awt.Color(87, 82, 62));
        jLabel10.setText("Phone no");

        tfaddress.setBackground(new java.awt.Color(242, 190, 36));
        tfaddress.setForeground(new java.awt.Color(87, 82, 62));

        addcustomerbutton.setBackground(new java.awt.Color(87, 82, 62));
        addcustomerbutton.setText("ADD");
        addcustomerbutton.setPreferredSize(new java.awt.Dimension(90, 30));
        addcustomerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomerbuttonActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(87, 82, 62));
        jLabel6.setText("Customer ID");

        jLabel7.setForeground(new java.awt.Color(87, 82, 62));
        jLabel7.setText("Name");

        getloanbutton.setBackground(new java.awt.Color(87, 82, 62));
        getloanbutton.setText("Get Loan");
        getloanbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        getloanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getloanbuttonActionPerformed(evt);
            }
        });

        opencurrentaccountbutton.setBackground(new java.awt.Color(87, 82, 62));
        opencurrentaccountbutton.setText("Open Current Account");
        opencurrentaccountbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        opencurrentaccountbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opencurrentaccountbuttonActionPerformed(evt);
            }
        });

        opensavingaccountbutton.setBackground(new java.awt.Color(87, 82, 62));
        opensavingaccountbutton.setText("Open Saving Account");
        opensavingaccountbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        opensavingaccountbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opensavingaccountbuttonActionPerformed(evt);
            }
        });

        jMenuBar1.setForeground(new java.awt.Color(87, 82, 62));

        JMenu1.setText("File");

        addCurrentAccountMI.setBackground(new java.awt.Color(242, 190, 36));
        addCurrentAccountMI.setText("Add Current Account");
        addCurrentAccountMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCurrentAccountMIActionPerformed(evt);
            }
        });
        JMenu1.add(addCurrentAccountMI);

        addSavingAccountMI.setBackground(new java.awt.Color(242, 190, 36));
        addSavingAccountMI.setText("Add Saving Account");
        addSavingAccountMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSavingAccountMIActionPerformed(evt);
            }
        });
        JMenu1.add(addSavingAccountMI);

        addLoanMI.setBackground(new java.awt.Color(242, 190, 36));
        addLoanMI.setText("Add Loan");
        addLoanMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLoanMIActionPerformed(evt);
            }
        });
        JMenu1.add(addLoanMI);

        jMenuBar1.add(JMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getloanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addcustomerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(opencurrentaccountbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opensavingaccountbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opencurrentaccountbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcustomerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getloanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opensavingaccountbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addcustomerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomerbuttonActionPerformed
        // TODO add your handling code here:
        String code = tfbranchcode.getText();
        if(bank.getBranch(code)!=null){
            String customerid = tfcustomerid.getText();
            if(bank.getBranch(code).getCustomer(customerid)==null){
                String name = tfname.getText();
                String address = tfaddress.getText();
                String phoneno = tfphoneno.getText();

                customer = new Customer(customerid,name,address,phoneno);
                branch = bank.getBranch(code);
                branch.addCustomer(customer);
                
                showMessageDialog(null, "Customerss is Added");
            }
            else{
                showMessageDialog(null, "Customer already Exist!", "ERROR", ERROR_MESSAGE);
            }
        }
        else{
            showMessageDialog(null, "Branch Didn't Found!", "ERROR", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addcustomerbuttonActionPerformed

    private void addCurrentAccountMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCurrentAccountMIActionPerformed
        // TODO add your handling code here:
        AddCurrentAccountFrame jFrame = new AddCurrentAccountFrame(bank,customer,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_addCurrentAccountMIActionPerformed

    private void addSavingAccountMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSavingAccountMIActionPerformed
        // TODO add your handling code here:
        AddSavingAccountFrame jFrame = new AddSavingAccountFrame(bank,customer,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_addSavingAccountMIActionPerformed

    private void addLoanMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLoanMIActionPerformed
        // TODO add your handling code here:
        AddLoanFrame jFrame = new AddLoanFrame(bank,customer,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_addLoanMIActionPerformed

    private void getloanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getloanbuttonActionPerformed
        // TODO add your handling code here:
        AddLoanFrame jFrame = new AddLoanFrame(bank,customer,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_getloanbuttonActionPerformed

    private void opencurrentaccountbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opencurrentaccountbuttonActionPerformed
        // TODO add your handling code here:
       AddCurrentAccountFrame jFrame = new AddCurrentAccountFrame(bank,customer,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_opencurrentaccountbuttonActionPerformed

    private void opensavingaccountbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opensavingaccountbuttonActionPerformed
        // TODO add your handling code here:
        AddSavingAccountFrame jFrame = new AddSavingAccountFrame(bank,customer,branch);
        jFrame.setVisible(true);
    }//GEN-LAST:event_opensavingaccountbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JMenuItem addCurrentAccountMI;
    private javax.swing.JMenuItem addLoanMI;
    private javax.swing.JMenuItem addSavingAccountMI;
    private javax.swing.JButton addcustomerbutton;
    private javax.swing.JButton getloanbutton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton opencurrentaccountbutton;
    private javax.swing.JButton opensavingaccountbutton;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JTextField tfbranchcode;
    private javax.swing.JTextField tfcustomerid;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfphoneno;
    // End of variables declaration//GEN-END:variables
}
