/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_Manager;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sheharyar saeed 190880 
 * BSSE B - 4
 */
public class AddLoanFrame extends javax.swing.JFrame {
    Bank bank;
    Customer customer;
    Branch branch;
    /**
     * Creates new form AddLoanFrame
     */
    AddLoanFrame() {
        initComponents();
    }
    AddLoanFrame(Bank bnk) {
        initComponents();
        bank = bnk;
    }
    AddLoanFrame(Bank bnk,Customer cust , Branch brnch) {
        initComponents();
        bank = bnk;
        customer = cust;
        tfcustomerid.setText(customer.Cust_ID);
        branch = brnch;
        tfbranchcode.setText(branch.Branch_Code);
        tfloanno.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfloanamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfbranchcode = new javax.swing.JTextField();
        tfloanno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfloantype = new javax.swing.JTextField();
        getloanbutton = new javax.swing.JButton();
        tfcustomerid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfemi = new javax.swing.JTextField();
        tfprepayment = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfloanamount.setBackground(new java.awt.Color(242, 190, 36));
        tfloanamount.setForeground(new java.awt.Color(87, 82, 62));

        jLabel4.setForeground(new java.awt.Color(87, 82, 62));
        jLabel4.setText("Branch Code");

        jLabel1.setForeground(new java.awt.Color(87, 82, 62));
        jLabel1.setText("Loan No");

        jLabel2.setForeground(new java.awt.Color(87, 82, 62));
        jLabel2.setText("Amount");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 82, 62));
        jLabel3.setText("Add New Loan");

        tfbranchcode.setBackground(new java.awt.Color(242, 190, 36));
        tfbranchcode.setForeground(new java.awt.Color(87, 82, 62));
        tfbranchcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbranchcodeActionPerformed(evt);
            }
        });

        tfloanno.setBackground(new java.awt.Color(242, 190, 36));
        tfloanno.setForeground(new java.awt.Color(87, 82, 62));

        jLabel5.setForeground(new java.awt.Color(87, 82, 62));
        jLabel5.setText("Type");

        tfloantype.setBackground(new java.awt.Color(242, 190, 36));
        tfloantype.setForeground(new java.awt.Color(87, 82, 62));

        getloanbutton.setBackground(new java.awt.Color(87, 82, 62));
        getloanbutton.setText(" GET LOAN");
        getloanbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        getloanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getloanbuttonActionPerformed(evt);
            }
        });

        tfcustomerid.setBackground(new java.awt.Color(242, 190, 36));
        tfcustomerid.setForeground(new java.awt.Color(87, 82, 62));

        jLabel7.setForeground(new java.awt.Color(87, 82, 62));
        jLabel7.setText("Customer ID");

        jLabel6.setForeground(new java.awt.Color(87, 82, 62));
        jLabel6.setText("Your EMI per month =");

        tfemi.setBackground(new java.awt.Color(242, 190, 36));
        tfemi.setForeground(new java.awt.Color(87, 82, 62));

        tfprepayment.setBackground(new java.awt.Color(242, 190, 36));
        tfprepayment.setForeground(new java.awt.Color(87, 82, 62));

        jLabel8.setForeground(new java.awt.Color(87, 82, 62));
        jLabel8.setText("Prepayment");

        jMenuBar1.setForeground(new java.awt.Color(87, 82, 62));

        JMenu1.setText("File");
        jMenuBar1.add(JMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfloantype, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfloanamount, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfloanno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfprepayment, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfemi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(getloanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfloanno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfloanamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfloantype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfprepayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(getloanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getloanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getloanbuttonActionPerformed
        // TODO add your handling code here:
        String code = tfbranchcode.getText();
        if(bank.getBranch(code)!=null){
            String customerid = tfcustomerid.getText();
            if(bank.getBranch(code).getCustomer(customerid)!=null){
                int loanno = Integer.parseInt(tfloanno.getText());
                if(loanno!=0 && bank.getBranch(code).getLoan(loanno)==null){
                
                    Double loanamount = Double.parseDouble(tfloanamount.getText());
                    String loantype = tfloantype.getText();
                    String prepayment = tfprepayment.getText();
        
                    branch = bank.getBranch(code);
        
                    Loan loan = new Loan(loanno,loanamount , loantype,branch);
                    
                    loan.prepayment(Double.parseDouble(prepayment));
                    tfemi.setText(String.valueOf(loan.getEMI()));
                    
                    branch.addLoan(loan);
        
                    showMessageDialog(null, "Loan is Added");
                }
                else{
                    showMessageDialog(null, "Incorrect ID or Loan ID already Exist!", "ERROR", ERROR_MESSAGE);
                }
            }
            else{
                showMessageDialog(null, "Customer Didn't Found!", "ERROR", ERROR_MESSAGE);
            }
        }
        else{
            showMessageDialog(null, "Branch Didn't Found!", "ERROR", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_getloanbuttonActionPerformed

    private void tfbranchcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbranchcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbranchcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLoanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddLoanFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JButton getloanbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tfbranchcode;
    private javax.swing.JTextField tfcustomerid;
    private javax.swing.JTextField tfemi;
    private javax.swing.JTextField tfloanamount;
    private javax.swing.JTextField tfloanno;
    private javax.swing.JTextField tfloantype;
    private javax.swing.JTextField tfprepayment;
    // End of variables declaration//GEN-END:variables
}
