/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_Manager;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author sheharyar saeed 190880 
 * BSSE B - 4
 */
public class AddSavingAccountFrame extends javax.swing.JFrame {
    Bank bank;
    Customer customer;
    Branch branch;
    /**
     * Creates new form AddAccountFrame
     */
     AddSavingAccountFrame() {
        initComponents();
    }
     AddSavingAccountFrame(Bank bnk) {
        initComponents();
        bank = bnk;
    }
     AddSavingAccountFrame(Bank bnk,Customer cust, Branch brnch) {
        initComponents();
        bank = bnk;
        customer = cust;
        tfcustomerid.setText(customer.Cust_ID);
        branch = brnch;
        tfbranchcode.setText(branch.Branch_Code);
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        tfDoO.setText(dateFormat.format(date));
        tfaccountno.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfbranchcode = new javax.swing.JTextField();
        tfaccountbalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfaccountno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addaccountbutton = new javax.swing.JButton();
        tfDoO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfminimumbalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfcustomerid = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfbranchcode.setBackground(new java.awt.Color(242, 190, 36));
        tfbranchcode.setForeground(new java.awt.Color(87, 82, 62));

        tfaccountbalance.setBackground(new java.awt.Color(242, 190, 36));
        tfaccountbalance.setForeground(new java.awt.Color(87, 82, 62));

        jLabel1.setForeground(new java.awt.Color(87, 82, 62));
        jLabel1.setText("Account No");

        jLabel2.setForeground(new java.awt.Color(87, 82, 62));
        jLabel2.setText("Balance");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 82, 62));
        jLabel3.setText("Add New Saving Account");

        tfaccountno.setBackground(new java.awt.Color(242, 190, 36));
        tfaccountno.setForeground(new java.awt.Color(87, 82, 62));

        jLabel4.setForeground(new java.awt.Color(87, 82, 62));
        jLabel4.setText("Branch Code");

        addaccountbutton.setBackground(new java.awt.Color(87, 82, 62));
        addaccountbutton.setText("ADD");
        addaccountbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        addaccountbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccountbuttonActionPerformed(evt);
            }
        });

        tfDoO.setBackground(new java.awt.Color(242, 190, 36));
        tfDoO.setForeground(new java.awt.Color(87, 82, 62));

        jLabel5.setForeground(new java.awt.Color(87, 82, 62));
        jLabel5.setText("Minimun Balance");

        jLabel6.setForeground(new java.awt.Color(87, 82, 62));
        jLabel6.setText("Date of Opening");

        tfminimumbalance.setBackground(new java.awt.Color(242, 190, 36));
        tfminimumbalance.setForeground(new java.awt.Color(87, 82, 62));

        jLabel7.setForeground(new java.awt.Color(87, 82, 62));
        jLabel7.setText("Customer ID");

        tfcustomerid.setBackground(new java.awt.Color(242, 190, 36));
        tfcustomerid.setForeground(new java.awt.Color(87, 82, 62));

        jMenuBar1.setForeground(new java.awt.Color(87, 82, 62));

        JMenu1.setText("File");
        jMenuBar1.add(JMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(addaccountbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDoO, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfminimumbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfaccountno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfbranchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfaccountno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfaccountbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfminimumbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDoO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(addaccountbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addaccountbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccountbuttonActionPerformed
        // TODO add your handling code here:
        String code = tfbranchcode.getText();
        if(bank.getBranch(code)!=null){
            String customerid = tfcustomerid.getText();
            if(bank.getBranch(code).getCustomer(customerid)!=null){
                String accno = tfaccountno.getText();
                if(!accno.isEmpty() && bank.getBranch(code).getAccount(accno)==null && bank.getBranch(code).getCustomer(customerid).getSA()!=null){
                    double balance = Double.parseDouble(tfaccountbalance.getText());
                    double minbalance = Double.parseDouble(tfminimumbalance.getText());
                    if(balance>minbalance){
                        String doo = tfDoO.getText();

                        branch = bank.getBranch(code);

                        Saving_Account savingaccount = new Saving_Account();
                        savingaccount.addCustomer(accno, balance, minbalance, doo, branch,customer);
                    
                        bank.getBranch(code).getCustomer(customerid).setSA(savingaccount);
                            
                        branch.addAccount(savingaccount);

                        showMessageDialog(null, "Saving Account is Added");
                        this.dispose();
                    }
                    else{
                        showMessageDialog(null, "Balance is less then Min Balance!", "ERROR", ERROR_MESSAGE);
                    }
                }
                else{
                    showMessageDialog(null, "Incorrect ID or Account already Exist!", "ERROR", ERROR_MESSAGE);
                }
            }
            else{
                showMessageDialog(null, "Customer Didn't Found!", "ERROR", ERROR_MESSAGE);
            }
        }
        else{
            showMessageDialog(null, "Branch Didn't Found!", "ERROR", ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_addaccountbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSavingAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSavingAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSavingAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSavingAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddSavingAccountFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JButton addaccountbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tfDoO;
    private javax.swing.JTextField tfaccountbalance;
    private javax.swing.JTextField tfaccountno;
    private javax.swing.JTextField tfbranchcode;
    private javax.swing.JTextField tfcustomerid;
    private javax.swing.JTextField tfminimumbalance;
    // End of variables declaration//GEN-END:variables
}
