/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bank_Manager;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author sheharyar saeed 190880 
 * BSSE B - 4
 */
public class MainWindow extends javax.swing.JFrame {
    Bank bank;
    /**
     * Creates new form MainWindow
     */
     MainWindow() {
        initComponents();
        tfbankname.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfbankcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfbankname = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        addbranchbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        addBranchMI = new javax.swing.JMenuItem();
        addCustomerMI = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Bank_Manager/BankManager.png")).getImage());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 190, 36));
        jLabel1.setText("BANK MANAGER");

        jLabel2.setForeground(new java.awt.Color(87, 82, 62));
        jLabel2.setText("Bank Code");

        tfbankcode.setBackground(new java.awt.Color(242, 190, 36));
        tfbankcode.setForeground(new java.awt.Color(87, 82, 62));

        jLabel4.setForeground(new java.awt.Color(87, 82, 62));
        jLabel4.setText("Bank Name");

        tfbankname.setBackground(new java.awt.Color(242, 190, 36));
        tfbankname.setForeground(new java.awt.Color(87, 82, 62));

        savebutton.setBackground(new java.awt.Color(87, 82, 62));
        savebutton.setText("Save");
        savebutton.setPreferredSize(new java.awt.Dimension(100, 30));
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        addbranchbutton.setBackground(new java.awt.Color(87, 82, 62));
        addbranchbutton.setText("Add Branch");
        addbranchbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        addbranchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbranchbuttonActionPerformed(evt);
            }
        });

        jMenuBar1.setForeground(new java.awt.Color(87, 82, 62));

        JMenu1.setText("File");

        addBranchMI.setBackground(new java.awt.Color(242, 190, 36));
        addBranchMI.setText("Add Branch");
        addBranchMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchMIActionPerformed(evt);
            }
        });
        JMenu1.add(addBranchMI);

        addCustomerMI.setText("Add Customer");
        addCustomerMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMIActionPerformed(evt);
            }
        });
        JMenu1.add(addCustomerMI);

        jMenuBar1.add(JMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfbankcode, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfbankname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(addbranchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfbankname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfbankcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbranchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBranchMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchMIActionPerformed
        // TODO add your handling code here:
         if(bank!=null){
            AddBranch jFrame = new AddBranch(bank);
            jFrame.setVisible(true);
        }
        else{
            showMessageDialog(null, "No Bank Added yet!", "ERROR", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBranchMIActionPerformed

    private void addCustomerMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMIActionPerformed
        // TODO add your handling code here:
         if(!bank.branchlist.isEmpty()){
            AddCustomerFrame jFrame = new AddCustomerFrame(bank);
            jFrame.setVisible(true);
        }
        else{
            showMessageDialog(null, "No Branch Added yet!", "ERROR", ERROR_MESSAGE);
        }
         
    }//GEN-LAST:event_addCustomerMIActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        String bankname = tfbankname.getText();
        String bankcode = tfbankcode.getText();
        
        bank = new Bank(bankname,bankcode);
        showMessageDialog(null, "Bank is Added");
    }//GEN-LAST:event_savebuttonActionPerformed

    private void addbranchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbranchbuttonActionPerformed
        // TODO add your handling code here:
        if(bank!=null){
            AddBranch jFrame = new AddBranch(bank);
            jFrame.setVisible(true);
        }
        else{
            showMessageDialog(null, "No Bank Added yet!", "ERROR", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addbranchbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JMenuItem addBranchMI;
    private javax.swing.JMenuItem addCustomerMI;
    private javax.swing.JButton addbranchbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField tfbankcode;
    private javax.swing.JTextField tfbankname;
    // End of variables declaration//GEN-END:variables
}
